### ISSUE TITLE
Compiling causing entire computer to crash

### ISSUE THREAD

**Issue by longboarder241** [Tydragon00/asteroid-os-pokedex#1]
I initally tried to compile this using one of my lightweight laptops with 4gb of ram and at 83% it crashed it.  in lieau of this I went to my machine with 16gb of ram as it typically compiles anything no problem and once the progress hit 83% on it, it also crashed the machine.  I made sure to do a bleachbit -c system.memory to allow as much allocation as possible and I'm using a minimalistic window manager to also save on resources.  Would it be possible to make a script for lower ram machines or optimize the compilation process so its more accessible?  If not it's totally fine I just thought I'd ask.

**Comment by Tydragon00** [comment]
Which script crashes the machine?
